### ISSUE TITLE
Opening one staking accordion  opens all staking card accordions

### ISSUE THREAD

**Issue by 0xBriz** [vertekfi/dex-frontend#10]
All of the accordions seem to be linked through a parent component. Looks odd when they all open when one was intended.

![image](https://user-images.githubusercontent.com/98397602/212794934-7344d7fe-b88b-4cf7-bfa6-5f4d97846f20.png)

**Comment by harleen-m** [comment]
This can be fixed by adding `align-items: start;` on the grid container or `margin-bottom: auto;` on the children.
