### ISSUE TITLE
Users cannot edit their votes after 10 days

### ISSUE THREAD

**Issue by harleen-m** [vertekfi/dex-frontend#101]
Users cannot edit their votes after the 10 day period passes. The popup appears, but the number inside cannot be changed.

It might be related to https://github.com/vertekfi/dex-frontend/issues/100, but in this case clicking on a vote button brings up the popup. Just the number inside the popup cannot be edited.

**Comment by 0xKang** [comment]
i believe this has been resolved in the most recent update. At least it did for me. Are you still experiencing this?

**Comment by harleen-m** [comment]
It wasn't me specifically with this problem, but I'll ask around to get some confirmation!

**Comment by harleen-m** [comment]
Some people still experience this. My lock expires in 2 hours, I'll be able to test it then.

**Comment by harleen-m** [comment]
I can vote, other people can vote, so let's close this? 🎉
