### ISSUE TITLE
VPT token detector on Earn Page

### ISSUE THREAD

**Issue by KoenigKeule** [vertekfi/dex-frontend#107]
Can we have something like a token / VPT detector screening your wallet for forgetten VPTs to invest and or stake in the pools?
Edit: as reminder on the main site so you don't need to open the specific pool.

**Comment by harleen-m** [comment]
We already have this on the individual pool slash earn pages, right?

**Comment by KoenigKeule** [comment]
> We already have this on the individual pool slash earn pages, right?

Yeah we do
![image](https://user-images.githubusercontent.com/125215836/219806006-394ea712-06b9-4fa6-bb45-0a41a6357216.png)
