### ISSUE TITLE
Swap the complete balance

### ISSUE THREAD

**Issue by KoenigKeule** [vertekfi/dex-frontend#108]
Can we make it that way if you click on the total balance that the full balance automatically transfers to swap so you don't need to type the full number?
![image](https://user-images.githubusercontent.com/125215836/219850844-a92a9227-d9d9-497d-9201-ac22dffefd6d.png)

**Comment by 0xKang** [comment]
you can click 100% and it will input the value to swap everything.

**Comment by KoenigKeule** [comment]
> you can click 100% and it will input the value to swap everything.

Roger that, user error as I'm used to the other method
