### ISSUE TITLE
Vote power doesn't increase with increased stake

### ISSUE THREAD

**Issue by KoenigKeule** [vertekfi/dex-frontend#110]
From NB from UP

I noticed that the Votes you have don't change week to week even if you increase your veVRTK shares.  You have to vote again after 10days.  I am ok with not changing your voting percentage for 10 days but shouldn't the power of your percentage increase for the next epoch?  Mine only did once i changed my vote only then did all my shares come into play.
So compounding doesn't increase your voting power until you vote again.  The instructions state to resubmit the vote but you must wait 10days for that which more than likely means they won't get applied until the following epoch, maybe have the ability to resubmit the same vote counting your new shares for the next epoch even if its before your 10 days

=> this is what the website makes you think:  If you increase your position and you have 100% of your vote in Ames for example it will just give your vote more weight. => this is still the case, right?
This sentence is misleading
![image](https://user-images.githubusercontent.com/125215836/219974361-933f76f1-e8a1-467d-b541-7326656844f6.png)

**Comment by harleen-m** [comment]
I think the sentence applies. I believe we need to resubmit our vote when we increase our voting power.
