### ISSUE TITLE
Bribing UI Improvements

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-frontend#112]
Have a list of improvements for Bribing UI/UX, will list them here 👍 

### Bribe Symbol
- These symbols are cute but rather ugly, not really in line with the sleekness of our dApp. Perhaps we could go with something more subtle. Or if we really want to be gaudy, how about a spinning $ sign?
- Posted some suggestions so u get the idea ^^

![image](https://user-images.githubusercontent.com/106936065/222152571-f50fcb71-e6af-488f-ae68-17a16afb75de.png)
![image](https://user-images.githubusercontent.com/106936065/222153169-c332b1e3-d6f0-440c-9ee3-cea8a4f23a05.png)
![image](https://user-images.githubusercontent.com/106936065/222153206-cee1c55a-4377-4ebc-9b0a-d02034de0484.png)
https://cdn.dribbble.com/users/1518535/screenshots/7943843/media/1f4157b81b12c86da44b0e4afb688aa8.gif

---

### Bribe Symbol Popup
- This is also kinda ugly
- I think it should follow the popup style of the APRs

![image](https://user-images.githubusercontent.com/106936065/222155566-59120f06-8162-4f74-aedc-3ff427a0a4a0.png)
![image](https://user-images.githubusercontent.com/106936065/222155822-a4aca12e-9486-440b-93b7-9c3afe13cc7d.png)

---

### Voting Tooltip
- This should probably also follow the popup style of the APRs OR the popup style of the token images. You can decide which is nicer.
- Take note: Red means next epoch is lower than this epoch. Green means its higher than this epoch. Keep that color indication 👍 

![image](https://user-images.githubusercontent.com/106936065/222156142-b2d098eb-9c4c-4ae5-86a8-c8db51ea3dd2.png)
![image](https://user-images.githubusercontent.com/106936065/222156406-144bbff4-6f04-4d13-9810-6e50488bd6e4.png)

---

### Add Bribe Button
- This is nice and big, so its visually obvious. It could look a bit better though. Not sure how.
- Perhaps the style of the button could be different from all the other buttons on the dApp? Like a unique glow or pulsating glow when hovered over?

![image](https://user-images.githubusercontent.com/106936065/222156617-f8ec6f4a-18ee-4fc2-b9b1-878b2ced2915.png)

---

### Add Bribe Modal
- Add bribe modal needs a visual rework
- Should follow the styling of the other modals of the dApp
- After selecting a gauge and a bribe token, the dropdown selector still looks like nothing has been selected. There should be a visual indicator that "you have chosen something for this field" if you get what i mean.

![image](https://user-images.githubusercontent.com/106936065/222156969-ec69eb18-4e85-4d0e-840d-b65654193721.png)
![image](https://user-images.githubusercontent.com/106936065/222157105-b3cb508c-0a69-4b32-9754-2c91b1eebb1a.png)

---

### Bribe Column Display
- Now looking at the UI a bit more, i believe this column should show the total $ value of bribes on that gauge. It will look a lot more juicy and tempting to get into the volta for new users who come to this page and see a bunch of monies up for grabs.

![image](https://user-images.githubusercontent.com/106936065/222208574-b89471d6-2e6c-49c1-97a6-e3146d031691.png)

---

### Total Bribes Value
- There should be a "Total Bribes This Epoch" counter that shows the global $ value of all bribes for this epoch
- Again, i know its not imperative to core functionality of the bribes, but these are the kind of things that will allows us to push to market and get people to ape in

**Comment by harleen-m** [comment]
I'll try to narrow this down.
- [ ] bribe symbol to be replaced
- [ ] bribe symbol popup to be standardized
- [ ] voting tooltip style to be updated (APR style or token images style)
- [ ] Add Bribe button to be sparkled (not sure how yet)
- [ ] Add Bribe modal to be standardized
- [ ] Add Bribe modal select fields to be fixed to show selected items
- [x] Bribe column display (now displaying total bribe value for this next 2 epochs)
- [ ] Total bribes this epoch showing total $ value of all bribes for current epoch

I hope I didn't miss anything, some of these might be already fixed, I'll update it accordingly while I go through it.

**Comment by 0xKang** [comment]
very nice @harleen-m 👍 For the last pointer u have there, there should be a global indicator on the top of the page somewhere, showing total bribes for this epoch. If thats what u meant, then gucci ^^
