### ISSUE TITLE
Current epoch bribes is missing in modal

### ISSUE THREAD

**Issue by SweeTouch** [vertekfi/dex-frontend#113]
![image](https://user-images.githubusercontent.com/38596528/222353645-6c7c5c9d-7724-4f16-b9da-085f0689560c.png)

**Comment by 0xKang** [comment]
i think this is fixed

![image](https://user-images.githubusercontent.com/106936065/222800198-37368b1d-dc3d-4ab6-a2e8-7e07f9d0c20c.png)

**Comment by 0xKang** [comment]
@0xBriz close this 👍

**Comment by 0xKang** [comment]
Im in now muahahaha. Closing this as completed 👍
