### ISSUE TITLE
Need VRTK icon next to price in header

### ISSUE THREAD

**Issue by 0xBriz** [vertekfi/dex-frontend#12]
Providing screenshot of the old site as an example

![image](https://user-images.githubusercontent.com/98397602/212905837-a528ee6a-8f41-4b20-8eec-164059ade921.png)

![image](https://user-images.githubusercontent.com/98397602/212905924-40a09d3b-dbdb-4674-ab31-61772bd81dba.png)

**Comment by 0xBriz** [comment]
> Additionally, that used to be a button that displayed information about the AEQ token, it was kinda useful.
> 
> Also I think the Vertek icon shouldn't be present by the wallet address and should be either replaced by some generated image or simply removed?
> 
> ![image](https://user-images.githubusercontent.com/119888996/214843752-a87d588a-4988-4c35-b4fd-8a662b0422c8.png)

That is actually a good point. Doesn't make much sense there. Was supposed to just be a fill in for the NFT icon from Beets. And I also liked the information context menu when clicking the token image from last site. Can you do me a favor and break those two out into separate issues then? Thanks

**Comment by jumpman23xx** [comment]
logo added
