### ISSUE TITLE
Locking dates

### ISSUE THREAD

**Issue by harleen-m** [vertekfi/dex-frontend#121]
The locking says "Minimum date (03/28/2024) must come before Maximum date (03/14/2024)."

Logically, that makes only a little sense. What if we reword it if possible? Something along the line "The lock can be extended to 03/14/2024 on or after 03/28/2023."

And here's my other issue, I believe the first date should be saying 03/28/2023, as otherwise that'd never happen.

What do you think?

**Comment by 0xKang** [comment]
im actually ok with that wording update. also agree that the first date should be 2023 not 2024. good catch @harleen-m

**Comment by harleen-m** [comment]
So upon further investigation this actually comes from the browser based on the `minLockEndDateTimestamp` and `maxLockEndDateTimestamp`. And there's a valid reason why the dates are as such.
