### ISSUE TITLE
Disappeared Bribes on Claim Page

### ISSUE THREAD

**Issue by KoenigKeule** [vertekfi/dex-frontend#126]
Investor has voted 2 epochs ago and got the Bribes for that epoch.
He hadn't re-voted the last epoch due to the cool-off.
Now his Bribe earnings have disappeared.
Wallet addy can be found in ticket 0028.

**Comment by 0xBriz** [comment]
Just pushed an update for this. Will wait for confirmation everything is good before closing this.

**Comment by harleen-m** [comment]
Now I don't see my latest bribes...

**Comment by harleen-m** [comment]
_Now_ I can see my bribes again. (The ones I received previous epoch.)

**Comment by harleen-m** [comment]
For me this is solved. But I didn't participate in the latest bribes, so I'm not 100% sure whether that's still an issue; though I successfully claimed bribes yesterday from the epoch before last.

**Comment by 0xKang** [comment]
We've only had 1 other report of disappearing bribes. i have resolved that with the user directly, and asked him to monitor if it continues into the future.
