### ISSUE TITLE
Update metadata and analytics configuration in _document.tsx

### ISSUE THREAD

**Issue by 0xQuartizer** [vertekfi/dex-frontend#129]
**Background**

As a developer, I want to update the metadata and analytics configuration in the _document.tsx file to provide accurate information and improve SEO performance.

**Tasks**

1. Update the og:title to "Vertek DEX - Advanced Decentralized Exchange on BNB Chain."
2. Replace the og:description with "Vertek is the primary Balancer-style DEX on BNB Chain, supporting multi-token pools, rewards, and weighted token compositions."
3. Add the provided og:image (https://drive.google.com/file/d/1BnKUXxNBslrZrYOgt-2yR6qQBP5j8kab/view?usp=share_link) to the repository and update the reference in the _document.tsx file.
4. Verify if the Google Analytics key (g-key) is set or if one is needed. Leave a comment on the issue with the findings.

**Notes**

- File to update: pages/_document.tsx
- Check if there are other files that require updating (for example robots.txt is setup correctly?)
- Leave a comment on the issue with the findings.

**Comment by 0xKang** [comment]
Resolved 💯  good work
