### ISSUE TITLE
Button routing from Vote page to VRTK-BNB pool page throws error

### ISSUE THREAD

**Issue by 0xBriz** [vertekfi/dex-frontend#16]
Appears to be using the wrong pool id in the URL

![image](https://user-images.githubusercontent.com/98397602/214152087-97e7a01d-8f06-4fdc-8b1e-d5b9bf5b32ba.png)

![image](https://user-images.githubusercontent.com/98397602/214152369-6f8b7f4f-5b69-4be8-8fe2-f0d4a5707ab6.png)

![image](https://user-images.githubusercontent.com/98397602/214151902-db70d647-abf4-4a8c-bbe2-81a9b2759f12.png)

**Comment by 0xBriz** [comment]
Indeed

![image](https://user-images.githubusercontent.com/98397602/214152928-3517c621-9de5-4a31-a0dc-5cb5a0188363.png)

**Comment by jumpman23xx** [comment]
Im going to just bypass this duct-tape approach with the PID and have the button trigger the liquidity modal.
