### ISSUE TITLE
Create A Pool doesn't work

### ISSUE THREAD

**Issue by harleen-m** [vertekfi/dex-frontend#22]
Create a pool button opens a modal but additional tokens can't be added and two different tokens can't be selected at the same time. Preview button doesn't work either.

**Comment by harleen-m** [comment]
bb7ff3ff5ebf29c7d0671ef2fe2ee1e5f6857177 made this void.

**Comment by 0xKang** [comment]
yap, they're wanting to release the core pools in full first before opening up this functionality
