### ISSUE TITLE
My Investments on Home Page

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-frontend#27]
![image](https://user-images.githubusercontent.com/106936065/214822178-97b3a0be-8e61-4a86-8f0f-14ab40a530c6.png)

Theres a "My Investments" list that populates on the Home page. This shouldnt be here. Before this it didnt even show up coz the pools were not created i assume, but this My Investments thing should probably be under either the EARN or CLAIM tabs.

Also theres the reference to BPTs again lol^^

**Comment by jumpman23xx** [comment]
i sent this to the abyss
