### ISSUE TITLE
Voting page VE deposit modal

### ISSUE THREAD

**Issue by 0xBriz** [vertekfi/dex-frontend#3]
We need a modal that allow users to lock their VRTK-BNB pool tokens into the Voting Escrow contract. It should follow the same setup as the previous Vue version.

![image](https://user-images.githubusercontent.com/98397602/212088079-56a376a2-6a66-4359-98b5-1ed1a63a345b.png)

**Comment by jumpman23xx** [comment]
Handled, in process w/ you of connecting data
