### ISSUE TITLE
Pop-up for the VRTK price in the header

### ISSUE THREAD

**Issue by harleen-m** [vertekfi/dex-frontend#31]
We should make the VRTK price in the header into a button that would display a pop-up with VRTK info upon clicking. The pop-up can display the following:

- TVL
- VRTK price
- Market cap
- Circulating supply
- Swap fees last 24h
- Swap volume last 24h

![image](https://user-images.githubusercontent.com/119888996/214843752-a87d588a-4988-4c35-b4fd-8a662b0422c8.png)

As mentioned in https://github.com/vertekfi/dex-frontend/issues/12#issuecomment-1404989144.

**Comment by 0xKang** [comment]
This is a good idea 👍

**Comment by 0xBriz** [comment]
I set up a basic one and wired the data to it. Jump is finishing the styling for it now. Will be live in a bit
