### ISSUE TITLE
Vertek token icon is too heavy

### ISSUE THREAD

**Issue by harleen-m** [vertekfi/dex-frontend#34]
1 MB for just an icon seems way too much. Any chance of converting the bellow image into an svg and using that instead?

https://raw.githubusercontent.com/vertekfi/token-list/786c88566c8249415294d4fc73274559c99b15df/images/vertek-token-round.png

![image](https://raw.githubusercontent.com/vertekfi/token-list/786c88566c8249415294d4fc73274559c99b15df/images/vertek-token-round.png)

**Comment by 0xKang** [comment]
This has been resolved, can close this issue 👍
