### ISSUE TITLE
"Learn More" broken link

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-frontend#35]
![image](https://user-images.githubusercontent.com/106936065/215165136-d24f1623-42e3-4f9c-b6cd-3b5edb50595b.png)

When connecting wallet, this "Learn More" button should link to: https://medium.com/blockchain/crypto-wallets-explained-f9199e621366

right now it just links back to Vertek home page

**Comment by harleen-m** [comment]
@0xBriz, if you can confirm the link, I could make a PR to update that.

**Comment by 0xKang** [comment]
i confirm that link

**Comment by harleen-m** [comment]
This is now fixed.

**Comment by jumpman23xx** [comment]
Closed thanks to harleen!
