### ISSUE TITLE
Voting page modal to add VRTK-BNB liquidity

### ISSUE THREAD

**Issue by 0xBriz** [vertekfi/dex-frontend#4]
There is already a modal that serves this purpose. It's used in the pool single view and should be able to be reused in some way. The existing modal component has a button to open itself as apart of its code. May need to modify that. Button that should trigger this modal is here: 
![image](https://user-images.githubusercontent.com/98397602/212089994-e98945c6-4b21-43d6-81bb-4c83ee54db47.png)

**Comment by jumpman23xx** [comment]
This was addressed by linking to VRTK-BNB, but noting separately that we can trigger the modal and will port this in.
