### ISSUE TITLE
Pool Pages, Investments tab visual bugs

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-frontend#41]
![image](https://user-images.githubusercontent.com/106936065/215270743-85ef936c-8a8b-46a6-9780-1750c8fcca6c.png)
![image](https://user-images.githubusercontent.com/106936065/215270631-a10a6da3-4ede-4283-8a94-9aff5e6bfdc2.png)
![image](https://user-images.githubusercontent.com/106936065/215270778-a48da430-44ab-4f35-a68c-6d7067b5aeda.png)
![image](https://user-images.githubusercontent.com/106936065/215270784-9e1c60d3-978b-45da-a012-dd00949c0616.png)

On the individual pool pages, when clicking Investments, everything displays quite nicely if the pool has only 2 tokens. However, if there are more than 2 tokens in the pool, things get weird and text gets pushed out of the box.

Also, the data is looping still^^

**Comment by jumpman23xx** [comment]
all set
