### ISSUE TITLE
Only UP pool on pools page icon issue

### ISSUE THREAD

**Issue by harleen-m** [vertekfi/dex-frontend#42]
Only UP pool sometimes shows xAmes icon. Harder to reproduce. Sometimes going to a different pool (e.g. Pure Serenity) and back triggers this issue.

![image](https://user-images.githubusercontent.com/119888996/215273941-c34cf0bb-0c4a-4ea4-87fc-e7c53f10319d.png)

**Comment by jumpman23xx** [comment]
Noted. Once we get data pull properly set will see if this is still issue. Keeping it open until then.

**Comment by jumpman23xx** [comment]
good to go now
