### ISSUE TITLE
Show gauge fees

### ISSUE THREAD

**Issue by 0xBriz** [vertekfi/dex-frontend#44]
We need some indication of the deposit/withdraw fees near stake/unstake for pools.

![image](https://user-images.githubusercontent.com/98397602/215509906-cccb54c6-b9c4-424b-b75e-d9744d895619.png)

**Comment by 0xBriz** [comment]
This will require updating the frontend GQL query for pool staking data to include the gauge fees

**Comment by jumpman23xx** [comment]
done
