### ISSUE TITLE
Nav bar 2 bridges

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-frontend#48]
![image](https://user-images.githubusercontent.com/106936065/215966132-03f77254-a0ca-47ff-ab76-bc97f40e6397.png)

There are 2 **Bridge** tabs in the nav bar. Both bring up the same page https://www.vertek.exchange/bridge

Keep the one at the far end.

**Comment by Thefox797** [comment]
Seems to be fixed now. For me it only shows 1 now
