### ISSUE TITLE
Home Page edits

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-frontend#49]
![image](https://user-images.githubusercontent.com/106936065/215967037-c1c3252a-0978-418f-afe3-c9f06231262f.png)

Just a couple of edits for the top of the **Home** page:

- Remove "Welcome To"
- Change undertext to:
          "The pinnacle of panoptic evolution in Decentralized Exchanges"
                 "Choose your investment reality. Get integrated."
- Sexify VERTEK logo

**Comment by harleen-m** [comment]
I believe Vertek should be lowercased here, also the font doesn't have the same properties as the one in the actual logo, maybe the text could be replaced by the actual logo?

Additionally, in my opinion the text underneath could benefit from a taller line-height? Just a thought.

![image](https://user-images.githubusercontent.com/119888996/216322375-fe1182f0-a53c-49ae-b562-defa99f6f526.png)
