### ISSUE TITLE
Voting page modal to allow users to modify existing locks

### ISSUE THREAD

**Issue by 0xBriz** [vertekfi/dex-frontend#5]
Users need to be able to 

- Extend their lock time
- Increase the amount of their current lock
- Both at the same time

In the previous repo this was handle by the same modal/view that handles a users initial deposit. It passes values to say whether this is a new lock or one being updated. That code can be used for reference to implement in current repo.

![image](https://user-images.githubusercontent.com/98397602/212090431-3107376d-cf81-4581-ac01-3c553b032bde.png)
![image](https://user-images.githubusercontent.com/98397602/212091648-2e4663d8-0be0-4520-b616-1c4d7b8bbe24.png)

**Comment by jumpman23xx** [comment]
We're working to finalize the functions here so closing
