### ISSUE TITLE
Vi Vertek Vincit gauge buttons change

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-frontend#51]
![image](https://user-images.githubusercontent.com/106936065/216094895-49495944-58f5-472f-86fb-6d6e9010c6dd.png)
![image](https://user-images.githubusercontent.com/106936065/216094917-2d561b16-5e79-4721-8bca-98fe2723dd9c.png)

For the Main Pool only (Vi Vertek Vincit | VRTK-WBNB) there should not be the **Stake/Unstake** buttons or deposit fees, because users cannot stake into the gauge like the normal gauges. Instead, the only way to earn with VRTK-WBNB is to lock it in the Volta (veVRTK Voting system), so there should be like a button in place of the **Stake/Unstake** buttons that links to the **Vote** page

Something like the card on the **Earn** page

**Comment by harleen-m** [comment]
This seems to be in place now: https://www.vertek.exchange/pool/0xdd64e2ec144571b4320f7bfb14a56b2b2cbf37ad000200000000000000000000
