### ISSUE TITLE
Volta f.e bugs

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-frontend#55]
![image](https://user-images.githubusercontent.com/106936065/216265937-91c8bcd3-fa0e-403e-80b2-15cb596f260f.png)

- $ value not showing
- the word _percent_ should just be the symbol '%'

**Comment by harleen-m** [comment]
The $ value is showing for me, it just takes a second to load. I submitted a pull request for the percent change (https://github.com/vertekfi/dex-frontend/pull/61).

**Comment by jumpman23xx** [comment]
All set
