### ISSUE TITLE
NAN% when staking into gauge

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-frontend#59]
![image](https://user-images.githubusercontent.com/106936065/216300342-aa9971ee-3a69-4167-a393-f6224e79f2dc.png)

getting $NAN% dollar value

**Comment by harleen-m** [comment]
Probably related to https://github.com/vertekfi/dex-frontend/issues/56 (referencing the same attribute?)

**Comment by 0xKang** [comment]
This has been resolved, can close this issue 👍
