### ISSUE TITLE
Footer is not globally sticky to the bottom of page

### ISSUE THREAD

**Issue by 0xBriz** [vertekfi/dex-frontend#6]
Seems each new page shows the footer not globally sticky and needing to be adjust within each view. We should update that then.
![image](https://user-images.githubusercontent.com/98397602/212092522-78d0817b-4516-432e-b543-c17b281b823f.png)

**Comment by jumpman23xx** [comment]
This should be handled, footer has been reworked and am unable to reproduce the issue from this end. Please lmk if not!

**Comment by harleen-m** [comment]
It's still an issue for me on the Claim page.
