### ISSUE TITLE
Swaps are not showing on pool pages

### ISSUE THREAD

**Issue by harleen-m** [vertekfi/dex-frontend#64]
Swaps are not showing on pool pages.

![image](https://user-images.githubusercontent.com/119888996/216385915-69b24c83-1dd1-45a4-8899-cc0dfb399cb1.png)

**Comment by Thefox797** [comment]
What pool Harleen? I've noticed some pools missing or populating very late. 
Up for example didn't had a tx but once they popped up it was a 3 hour old one.

**Comment by harleen-m** [comment]
I think it's all pools. Or at least I didn't see any pool where I could see some swaps.

**Comment by 0xKang** [comment]
@harleen-m i moved this to the backend issues git, it seems to be more related to there 👍

**Comment by 0xBriz** [comment]
![image](https://user-images.githubusercontent.com/98397602/218270351-53297465-0d0d-452a-b3a9-6c382bf83271.png)
