### ISSUE TITLE
No stake deposit fee on Amesonian Apex

### ISSUE THREAD

**Issue by harleen-m** [vertekfi/dex-frontend#66]
It seems there's no deposit fee on staking Ames-BUSD (advertised as 1%). The 1% withdrawal fee seems to be present.

![image](https://user-images.githubusercontent.com/119888996/216421171-e1c0dc06-b4bc-4dbf-a595-0f498b50323a.png)

**Comment by harleen-m** [comment]
The same for Serenity and Pebble pools. Possibly all the pools that have a deposit fee?

**Comment by 0xBriz** [comment]
The fee is taken from the pool tokens at deposit/withdraw and the user balance, and gauge total supply, are updated accordingly then. Can you check your balance in your wallet for what the gauge reports as your balance in the end? I just deposited 22.0981xx into the Ames gauge after seeing your comment. When viewing my balance I see it reported as 1% lower than the deposit amount.
![image](https://user-images.githubusercontent.com/98397602/216679908-eb24c87b-14aa-46eb-a597-cda1151e2634.png)

**Comment by 0xBriz** [comment]
Just ran a check and pulled on chain fee events from the contract and see the type and amount logged properly as well
![image](https://user-images.githubusercontent.com/98397602/216682087-4c509e83-3e50-4e12-b246-107bed4f5c39.png)


Let me know if you are seeing something different on your end. Appreciate you keeping an eye out on things

**Comment by harleen-m** [comment]
Aha, this is interesting! I just checked my wallet and the balance is indeed 1% lower. And when I try to withdraw the amount is also another 1% lower. I also checked other deposits I made and the numbers now do add up. So things are good, thank you!
