### ISSUE TITLE
Token description not showing on "Vote Page" 

### ISSUE THREAD

**Issue by Thefox797** [vertekfi/dex-frontend#68]
The token description isn't showing on the Vote page. It does work on the Earn page.

Vote page:
![afbeelding](https://user-images.githubusercontent.com/124088392/216471505-dc71341b-f617-448a-8999-e1160c22093a.png)

Earn Page: 
![afbeelding](https://user-images.githubusercontent.com/124088392/216471597-30063cfd-e769-4857-9b2a-ff4b2bf6012f.png)

**Comment by 0xBriz** [comment]
Should be live in a few
