### ISSUE TITLE
Annoying notifications

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-frontend#72]
These notification thingies dont disappear naturally. They also dont seem to be tracking properly i think. Those in the screenshot are all already confirmed. 

![image](https://user-images.githubusercontent.com/106936065/216769669-c9198182-572e-40e4-bf73-4e575e6fd246.png)

**Comment by harleen-m** [comment]
Is this still an issue? I wanna say I never had it happen.

**Comment by 0xKang** [comment]
This has been resolved.
