### ISSUE TITLE
Pagination touchups

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-frontend#73]
![image](https://user-images.githubusercontent.com/106936065/216773226-65c4a8eb-a0c5-43ea-8027-285aa44611a6.png)
![image](https://user-images.githubusercontent.com/106936065/216773270-81228352-554e-46a9-a04a-a4af9f2058e4.png)
![image](https://user-images.githubusercontent.com/106936065/216773356-63357a59-cd94-4b2c-81a0-c49760897fdc.png)

- The dark background for pagination bar is oversized
- Dropdown for "per page" is the old style white stuff lol, we wanna use the new type that u made thats more visible and looks nicer
- The **Vote** page also needs pagination
- Might wanna make the page counter box smaller, its a little jarring now

**Comment by jumpman23xx** [comment]
Should be good
