### ISSUE TITLE
Individual pool pages need an "About This Project" button

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-frontend#74]
![image](https://user-images.githubusercontent.com/106936065/216775505-cfa67166-a74c-40b2-baad-db97a8c7d133.png)

Right here, in this space, we can have an "About This Project" button, that opens a modal, that has a short description of the project (you can have it blank or with placeholder text for now). We will get projects to write these up for us.

Modal can look like the **Invest** one, but it doesnt need any buttons (except the X to close i suppose) and wont be hooked up to any smart contracts. It'll all just be text with some images, which the projects will give to us. 

![image](https://user-images.githubusercontent.com/106936065/216775682-13891327-9d5a-4897-8eb3-cfa38e9edf01.png)

**Comment by 0xBriz** [comment]
Base for this is in place and live(opens an empty modal). Will update as we move forward then
