### ISSUE TITLE
2 Claim tabs on Mobile

### ISSUE THREAD

**Issue by serenitycapital** [vertekfi/dex-frontend#75]

**Comment by serenitycapital** [comment]
![image](https://user-images.githubusercontent.com/104404965/216781767-77bd6a3a-c02f-4b78-8039-780ac1411515.png)

**Comment by harleen-m** [comment]
And 2 NFT Marketplaces and 2 Perpetuals. 🖤

**Comment by jumpman23xx** [comment]
Fixed, with some additional improvements
