### ISSUE TITLE
My Investments filter not displaying gauge balance

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-frontend#78]
The **My Investments** filter displays $ value balance for VPTs in wallet, but not the user's gauge balance. It should be showing VPT $ value in wallet + gauge deposit token $ value in wallet

**Note 1:** When users deposit into a gauge, they get a gauge deposit token, so perhaps its possible to track wallet balance of those, if reading their stake directly into the gauge is not feasible.

**Note 2:** We spoke previously about having 2 columns then. 1 for **VPT Balance** and 1 for **Gauge Deposit Balance** . I'll leave this up to you to decide how to implement for the best UI/UX experience.

End state: whichever is more accurate and easily implemented is the one we are going for.

![image](https://user-images.githubusercontent.com/106936065/217792635-54cbfcd8-bac5-47c5-a2b6-5009707ccd57.png)

**Comment by jumpman23xx** [comment]
all set
