### ISSUE TITLE
Decrease the animation effect on claim button hover

### ISSUE THREAD

**Issue by 0xBriz** [vertekfi/dex-frontend#8]
The claim buttons have the same issue the voting buttons had.  Where the button grows too large on hover on desktop. It causes the size of the containing table row to grow. Has a slightly jarring visual effect. Maybe a global style for buttons that will have this effect.

![image](https://user-images.githubusercontent.com/98397602/212301419-468624fd-2bae-460d-8177-cd6278a89405.png)

**Comment by jumpman23xx** [comment]
this was addressed with global thematic hover style of no more than transform scale 1.02.
