### ISSUE TITLE
Hover over tokens inconsistent UI/UX

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-frontend#80]
### Some UI updates for token icons

- Transparency when hovering over token icons on EARN page needs to be frosted glass like before, right now background interferes visually.
- Interestingly, when hovering over token icons on CLAIM and VOTE, the frosted glass background is there lol.
- Additionally, the weight % shows on EARN page but not on CLAIM and VOTE. The weight % should show always.

**So summary fix:**
- All instances of hovering over token icons should have frosted glass background
- All instances of hovering over token icons should also display weight % (EXCEPT for stablecoin pools. Stablecoin pools do not naturally have weights to stick to)

---

### Transparency Comparison & Missing Weight %

Clear Background:
![image](https://user-images.githubusercontent.com/106936065/217148032-7ec45e93-0123-47a0-8304-54f0048fe303.png)

Nice Frosted Glass Background:
![image](https://user-images.githubusercontent.com/106936065/217148155-a6a58e25-9252-41f6-ac20-a22926c8d738.png)

**Comment by 0xBriz** [comment]
Jump will have to sort out the glass window thing on earn. I tried but he has some custom styling in there I don't want to mess up

![image](https://user-images.githubusercontent.com/98397602/218270276-f5757f3e-cb03-428c-91b3-56c21d263042.png)
