### ISSUE TITLE
Claim button on pool pages not working (EDIT: Remove button+ pending rewards indicator. See comments)

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-frontend#83]
The **Claim Rewards** button on the individual pool pages are not working

### **EDIT: Remove button+ pending rewards indicator. See comments**

**_Button greyed out, and pending rewards stated as $0.00:_**
![image](https://user-images.githubusercontent.com/106936065/217788823-97049e81-40da-4f51-a2a0-60065527aa17.png)

**_Connected wallet obviously has rewards to claim:_**
![image](https://user-images.githubusercontent.com/106936065/217788938-02c4a93e-0745-4dc7-ac00-c1196a94a7d6.png)

**Comment by 0xBriz** [comment]
Forgot that was over there.  Beet did not have gauges for most of the time and used master chef. So the rewards setup is a bit different. If we want rewards claimable on individual pool page as well then some things will need to be reworked.

**Comment by 0xKang** [comment]
How jumanji is it? If its more the 1 day trek in the jungle, just hide the button and the **My pending rewards** indicator. We want to make the Claim page into a very nice dashboard, so having rewards claimable on individual pool pages is redundancy of the highest order.
