### ISSUE TITLE
decimals on vote page

### ISSUE THREAD

**Issue by SweeTouch** [vertekfi/dex-frontend#88]
Too many decimals 

![image](https://user-images.githubusercontent.com/38596528/218317216-0ce49473-06da-4e34-b0ed-d8f3ca37c501.png)

**Comment by 0xBriz** [comment]
This one is all you @SweeTouch. Make it happen lol

**Comment by 0xBriz** [comment]
Just checked and jump must have had this as part of update earlier today. Seems it's good. I'll open back up if you're seeing something different still.

![image](https://user-images.githubusercontent.com/98397602/218331693-a1c109f9-1295-435b-ae37-90730d8d1a2d.png)
