### ISSUE TITLE
My APR Difference

### ISSUE THREAD

**Issue by KoenigKeule** [vertekfi/dex-frontend#91]
1)the My APR shown right in front of me, is always showing the max possible value,  and it seems that I Have to go to hover menu to see my Real MY APR. The numbers difference is what it needs to the maximum multiplier of 2.5x it seems.

2) In addition, I don't have any veVRTK, but am still showing a 2.22x multiplier....and a higher APR listed than what the actual returns I am getting would seem to indicate. 
**=>**"This happened to me whenever I entered any pool. Before entering a pool, the APR hover breakdown said my boost multiplier is 1. Then as soon as I entered the pool, the multiplier showed over x2.  This was before I actually had any veVRTK.   Now I have actually have veVRTK so I can’t replicate the scenario." But if you haven't entered the pool at all, multiplier says 1x as it should be. Problems seems to be when the VPTs are staked, but without veVRTK.

Example Buddy system: Done with a wallet without ve. Multiplier Problem after staking
ALSO: In my main wallet with over 1% ve I have 137$ staked and got the 2.44x multiplier => is this supposed to happen? 
afaik max boost is when the % of ownership in the Volta AND the Core pool matches?
![image](https://user-images.githubusercontent.com/125215836/218798831-c8adbc47-423c-40bd-9735-98e3f4be1aa0.png)
![image](https://user-images.githubusercontent.com/125215836/218798893-df22fe69-f00f-4ff7-9f4d-e8b5b66eeccc.png)

3) Is it possible to add more contrast to the APR numbers to make them pop more? They are hard to read.

![APR](https://user-images.githubusercontent.com/125215836/218332063-e2a70506-28f3-4585-b90e-7d8497a19c09.png)
![APRII](https://user-images.githubusercontent.com/125215836/218332069-509ff4c5-c4df-4bbe-850a-75ae53ef5871.png)

**Comment by harleen-m** [comment]
Additionally, where does this 2.5x come from? The documentation says that it comes from people that didn't lock any veVRTK. But still it has to come from somewhere, so I wonder whether the multipliers aren't like this:

Min APR 0.4x - worst case for those who have no veVRTK staked.
Base APR 1x - no one has any veVRTK staked (unlikely).
Max APR 2.5x - best case for those who have enough veVRTK staked as long as there're enough people without staked veVRTK.

@0xBriz, @0xKang, what do you boys think? I noticed some people complained that their actual APR was way lower than the current "base" APR, approximately 50% lower. Then the above could explain it. I don't have any actual data to support this, just some food for thought.

**Comment by 0xBriz** [comment]
The first thing you're showing there definitely looks like a bug in how it's being calculated. Should be a quick fix. 

The possible 2.5x is made possible by how the gauge contracts calculate liquidity. The base is 0.4/40% like you mentioned. Then based on your amount of ve versus the total ve supply your "boost" is calculated.

I added my own comments to the vyper contract talking about it. The end is cut off but you can see it on line 384 in the LiquidityGaugeV5 contract.

![Screenshot_20230216-123147_Chrome](https://user-images.githubusercontent.com/98397602/219443387-599ba79d-9ff4-4051-9a4a-e7a167df8a07.jpg)
