### ISSUE TITLE
Claim Page The Three Amigos

### ISSUE THREAD

**Issue by KoenigKeule** [vertekfi/dex-frontend#92]
I am not invested in The Three Amigos Pool, but it is still displayed in the Claim section under Other Gauge earnings

![image](https://user-images.githubusercontent.com/125215836/218332333-4e722446-4304-488c-9ba3-03ec12702531.png)

**Comment by 0xBriz** [comment]
This is so people see what they are missing with extra rewards

**Comment by 0xBriz** [comment]
Meaning you should stop slacking and go ape

**Comment by 0xKang** [comment]
word

**Comment by KoenigKeule** [comment]
Ape confused, Error 404
