### ISSUE TITLE
Total amount of veVRTK

### ISSUE THREAD

**Issue by KoenigKeule** [vertekfi/dex-frontend#94]
On the dApp "Voting" page...It would be nice to see the total veVRTK listed on somewhere (even if someone does not currently have any veVRTK yet). It would be handy to help figure out how much they might want to get (and what it would cost them).

You could even make it real fancy and also list something like..."At current VRTK/WBNB prices, it would cost $xx.xx to create 1% of total veVRTK."

**Comment by jumpman23xx** [comment]
<img width="1471" alt="Screenshot 2023-02-12 at 5 53 41 PM" src="https://user-images.githubusercontent.com/102991359/218342264-7fc41cb6-f1ce-4501-bedd-53cc6a5029ed.png">

Site has display for veVRTK on top row of /voting. See 4th card.
