### ISSUE TITLE
container overflow on confirmation page

### ISSUE THREAD

**Issue by SweeTouch** [vertekfi/dex-frontend#96]
all in the title

![brave_2R8Ysg1Skx](https://user-images.githubusercontent.com/38596528/218360134-e835b214-65f5-45f7-aed2-8b8d3ff3e17b.png)

**Comment by jumpman23xx** [comment]
a fix to this was pushed on branch swapmodal; wider issue relates to visualization on the sor, but the resize of the swap transaction details modal should help
